[project]
name = "rsosh"
version = "0.1.0"
description = "Web Service with olimpiads RSOSH"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.11",
    "requests>=2.32.3",
    "sqlalchemy>=2.0.40",
    "uvicorn>=0.34.0",
]
